name: WorldFixerPlus
main: skh6075\worldfixerplus\Loader
author: AvasKr
version: 1.0.0
api: [3.0.0 , 4.0.0]
website: https://github.com/GodVas

permissions:
  world.fixer.permission:
    default: op
